server:
  port: 31001
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      uri: mongodb://root:1234@192.168.12.132:27017
      database: xc_cms
  freemarker:
    cache: false
    settings:
      template_update_delay: 0
  rabbitmq:
    host: 192.168.12.130
    port: 5672
    virtual-host: /xc
    username: xuecheng
    password: 1234
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:50102/eureka/   # Eureka服务端地址
    fetch-registry: true  # 开启服务发现功能
    register-with-eureka: true # 开启服务注册功能
  instance:
    prefer-ip-address: true # 是否采用ip地址作为注册中心的地址
    ip-address: 127.0.0.1 # ip地址
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
