server:
  port: 50201
  servlet:
    context-path: /api
spring:
  application:
    name: xc-govern-gateway
  redis:
    host: ${REDIS_HOST:192.168.12.132}
    port: ${REDIS_PORT:6379}
    timeout: 5000 #连接超时 毫秒
    jedis:
      pool:
        maxActive: 3
        maxIdle: 3
        minIdle: 1
        maxWait: -1 #连接池最大等行时间 -1没有限制
eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: ${EUREKA_SERVER:http://localhost:50102/eureka/}
  instance:
    prefer-ip-address:  true  #将自己的ip地址注册到Eureka服务中
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port} #指定实例id
ribbon:
  MaxAutoRetries: 2 #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试，如果eureka中找不到服务则直接走断路器
  MaxAutoRetriesNextServer: 3 #切换实例的重试次数
  OkToRetryOnAllOperations: false  #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的,所以设置为false
  ConnectTimeout: 5000  #请求连接的超时时间
  ReadTimeout: 6000 #请求处理的超时时间
zuul:
  routes: # 配置服务路由
    xc-service-learning:  # 路由id
      path: /learning/**          # 服务路由路径
      serviceId: xc-service-learning  # 微服务实例
      strip-prefix: false     # 是否去掉前缀,在zuul向微服务进行转发请求的时候是否去掉路由uri前缀 true: 在zuul进行代理转发的时候去掉路由前缀 false: 在zuul进行代理转发的时候不去掉路由前缀
      sensitiveHeaders:
      ignoreHeaders:          # 设置过滤头信息
    xc-service-manage-course:  # 课程微服务
      path: /course/**
      serviceId: xc-service-manage-course
      strip-prefix: false
      sensitiveHeaders:
    xc-service-manage-cms:
      path: /cms/**
      serviceId: xc-service-manage-cms
      strip-prefix: false
      sensitiveHeaderss:
    xc-service-base-filesystem:
      path: /sys/**
      serviceId: xc-service-base-filesystem
      strip-prefix: false
      sensitiveHeaders:
    xc-service-ucenter:
      path: /ucenter/**
      serviceId: xc-service-ucenter
      strip-prefix: false
      sensitiveHeaders:
    xc-service-manage-order:
      path: /order/**
      serviceId: xc-service-manage-order
      strip-prefix: false
      sensitiveHeaders:



