server:
  port: 31450
spring:
  application:
    name: xc-service-manage-media-processor
  data:
    mongodb:
      uri: mongodb://root:1234@192.168.12.132:27017
      database: xc_media
#rabbitmq配置
  rabbitmq:
    host: 192.168.12.130
    port: 5672
    username: xuecheng
    password: 1234
    virtual-host: /xc
xc-service-manage-media:
  mq:
    queue-media-video-processor: queue_media_video_processor
    routingkey-media-video: routingkey_media_video
  video-location: C:/workdir/javascript/video/
  ffmpeg-path: C:/software/Ffmpeg-win64/bin/ffmpeg.exe