server:
  port: 31200
spring:
  application:
    name: xc-service-manage-course
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/xc_course?serverTimezone=GMT%2B8&amp
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
  jpa:
    database: mysql   # 数据库类型
    database-platform: org.hibernate.dialect.MySQLDialect # 数据库方言
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
pagehelper:
  helper-dialect: mysql
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:50102/eureka/
    fetch-registry: true # 开启服务发现
    register-with-eureka: true #  开启服务注册
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
course-publish:
  siteId: 5e834c817ec26d0a38f1fdb8
  pageWebPath: /course/detail/
  pagePhysicalPath: /course/detail/
  pageType: 1
  templateId: 5aec5dd70e661808240ab7a6
  dataUrl: http://localhost:31200/course/detail/view/
  previewUrl: http://www.xuecheng.com/cms/preview/
ribbon:
  eureka:
    enabled: true
  # MaxAutoRetries: 2 #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试
  # MaxAutoRetriesNextServer: 3 #切换实例的重试次数
  # OkToRetryOnAllOperations: false  #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作 没有实现幂等的情况下是很危险的,所以设置为false
  # ConnectTimeout: 5000  #请求连接的超时时间
  # ReadTimeout: 6000 #请求处理的超时时间

